language: node_js

node_js:
	- "node"

install:
	- npm install -g vuepress

script:
	- vuepress build && cd .vuepress/dist && echo 'architecturecoding.com' > CNAME

deploy:
	provider: pages
	skip-cleanup: true
	github-token: $GITHUB_ACCESS_TOKEN
	local-dir: .vuepress/dist
	on:
		tags: true
		all_branches: true
