language: node_js
node_js:
	- lts/*
install:
	- npm ci
script:
	- npm install -g vuepress
	- npm run docs:build && cd .vuepress/dist && echo 'architecturecoding.com' > CNAME
deploy:
	provider: pages
	skip_cleanup: true
	local_dir: docs/.vuepress/dist/
	token: $GITHUB_ACCESS_TOKEN # a token generated on github allowing travis to push code on you repository
	keep_history: true
	on:
		branch: master
